const types = {
  UPDATE_STUDENT: 'UPDATE_STUDENT',
  ADD_STUDENT: 'ADD_STUDENT',
  DELETE_STUDENT: 'DELETE_STUDENT',
  FETCH_STUDENT: 'FETCH_STUDENT',
  SHOW_LOADING: 'SHOW_LOADING',
  HIDE_LOADING: 'HIDE_LOADING',
  FETCH_STUDENTS_SUCCESS: 'FETCH_STUDENTS_SUCCESS',
  FETCH_STUDENTS_FAILED: 'FETCH_STUDENTS_FAILED',
  ADD_STUDENT_SUCCESS: 'ADD_STUDENT_SUCCESS',
  ADD_STUDENT_FAIL: 'ADD_STUDENT_FAIL',
  DELETE_STUDENT_SUCCESS: 'DELETE_STUDENT_SUCCESS',
  DELETE_STUDENT_FAIL: 'DELETE_STUDENT_FAIL',
  UPDATE_STUDENT_SUCCESS: 'UPDATE_STUDENT_SUCCESS',
  UPDATE_STUDENT_FAIL: 'UPDATE_STUDENT_FAIL',
  DISPLAY_FORM: 'DISPLAY_FORM',
  DISPLAY_FORM_SUCCESS: 'DISPLAY_FORM_SUCCESS'
};
export default types;
